# Generated by Django 5.0 on 2023-12-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='اسم الكورس')),
                ('time_start', models.TimeField(verbose_name='موعد بداية المحاضرة')),
                ('time_end', models.TimeField(verbose_name='موعد نهاية المحاضرة')),
                ('hours', models.IntegerField(verbose_name='عدد ساعات')),
                ('cotch', models.CharField(max_length=50, verbose_name='اسم المدرب')),
                ('place_descripe', models.TextField(verbose_name='وصف الموقع')),
                ('place_link', models.CharField(max_length=150, verbose_name='الموقع على الخريطة')),
                ('descripe_course', models.TextField(verbose_name='تفاصيل الكورس')),
                ('image', models.ImageField(upload_to='upload/%d/', verbose_name='الصورة')),
            ],
        ),
    ]
