# Generated by Django 5.0 on 2023-12-22 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم الرباعي')),
                ('phone_number', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('notes', models.TextField(verbose_name='ملاحظات')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coures', to='Courses.courses')),
            ],
        ),
    ]
